### ISSUE TITLE
Dummies break

### ISSUE THREAD

**Issue by ForTheWout** [ForTheCrown/FTC#21]
Husk dummies seem to break somehow. They lose their show-dmg-on-hit functionality and just stand there menacingly.
Current fix is killing them and spawning a new one.

**Comment by JulieWoolie** [comment]
Switched from directly caching the reference to the dummy entity to caching an `EntityIdentifier` instance. I believe the underlying `Entity` instance being unloaded and invalidated was the cause of the issue
